services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual em /app no container
      # Isso permite o live-reload do código e persiste o banco de dados SQLite
      - .:/app
    # O comando sobrescreve o CMD do Dockerfile para ambiente de desenvolvimento
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload